carla:
  host: "localhost"
  timeout: 30.0
  timestep: 0.05
  retries_on_error: 30
  res_x: 1280
  res_y: 720
  quality_level: "Epic"
  enable_rendering: true
  show_display: true

experiment:
  town: "Town10HD_Opt"
  hero_model: "vehicle.dodge.charger_2020"
  sensors: 
    camera:
      type: "sensor.camera.rgb"
      image_size_x: 800
      image_size_y: 600
      fov: 90
      transform: "0.5, 0, 1.65, 0, -10, 0"
    lidar:
      type: "sensor.lidar.ray_cast"
      range: 20
  weather: "ClearNoon"
  tm_hybrid_mode: false
  seed: true

