carla:
  host: "localhost"
  timeout: 30.0
  timestep: 0.05
  retries_on_error: 30
  res_x: 1280
  res_y: 720
  quality_level: "Epic"
  enable_rendering: true
  show_display: true

experiment:
  town: "Town10HD_Opt"
  weather: "ClearNoon"
  tm_hybrid_mode: false
  seed: true
